### ISSUE TITLE
Remontée de données sur les facteurs

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres-dashboard-backend#24]
En tant qu'administrateur du dashboard patrimoine, je souhaite être en mesure d'afficher des indicateurs sur les caractéristiques des facteurs présents dans les bouquets afin de pouvoir les intégrer dans un dashboard de KPI du projet ecosphères : 
- % de facteurs pour lesquels le jeux de donnée est disponible URL data gouv et url externe, tout bouquets confondus
- répartition des facteurs entre URL externe et data.gouv
 
 ToDo : 
Ajouter des compteurs dans la moulinette pour les catégories de facteurs suivants : 

- [x] facteurs vides "pas trouvés" dans les bouquets publiés
- [x] facteurs vides "pas cherchés" dans les bouquets publiés
- [x] facteurs avec URL externe dans les bouquets publiés
- [x] facteurs avec JDD data.gouv.fr (création d'un nouveau que sur les bouquets publiés)

Déjà existant : facteurs avec JDD data.gouv.fr existe déjà, mais sur tous les bouquets y compris brouillon.

**Comment by Thesauruv** [comment]
@DanFluture275 Ces statistiques émanent d'une demande du fonds qui nous finance, elles s'adressent d'abord à nos sponsors (profils pas particulièrement spécialistes) et non à un administrateur du dashboard patrimoine.
