### ISSUE TITLE
Remontées de données spécifiques sur les types d'organisation

### ISSUE THREAD

**Issue by DanFluture275** [ecolabdata/ecospheres-dashboard-backend#25]
En tant qu'administrateur du dashboard patrimoine, je souhaite être en mesure de configurer des indicateurs sur le type d'organisation moissonnées afin de pouvoir les inclure au dashboard KPI projet : 
- nombre d'organisations de type DDT moissonnées
- nombre d’organisations de type DREAL moissonnées
- nombre d’opérateurs de l’état moissonnées

To do : ajouter à la moulinette une  nouvelle colonne "type organisation" dans la table orga. 
Attention à avoir un libellé lisible pour superset

- se baser sur un grist référençant les types d'organisation et extraire les données de ce grist à partir de la moulinette
`https://grist.numerique.gouv.fr/o/ecospheres/k3YQHL3Bmrhm/Moissonnages/p/10`

**Comment by abulte** [comment]
Related https://github.com/ecolabdata/ecospheres/issues/493

**Comment by DanFluture275** [comment]
@Thesauruv : compléter le grist https://grist.numerique.gouv.fr/o/ecospheres/k3YQHL3Bmrhm/Moissonnages/p/10, remplir la colonne "Type" avec les libellés complets
