### ISSUE TITLE
Mismatch number of orgs vs universe

### ISSUE THREAD

**Issue by abulte** [ecolabdata/ecospheres-dashboard-backend#33]
Prod

```
❯ curl -s https://raw.githubusercontent.com/ecolabdata/ecospheres-universe/refs/heads/main/dist/organizations-prod.json|jq 'length'
170
```

```
dashboard_backend_prod=# select count(distinct(organization)) from catalog where deleted = false;
 count
-------
   174
(1 row)
```

```
dashboard_backend_prod=# select count(distinct(organization)) from metrics where date = '2024-12-12';
 count
-------
   174
(1 row)
```

**Comment by DanFluture275** [comment]
Et la metrique calculée vaut 175

<img width="1671" alt="image" src="https://github.com/user-attachments/assets/a3b0cff6-e0f5-4c4e-9b18-339af5ba45da" />

**Comment by abulte** [comment]
> Et la metrique calculée vaut 175

Celui-là c'est bon, il manque un `organization is not null` dans le Count.

**Comment by abulte** [comment]
Pour le reste (174 en base vs 170 dans le grist), ces organisations sont dans l'univers (aka ont des jeux de données dans le Topic) mais ne sont pas dans le Grist :

- https://www.data.gouv.fr/fr/organizations/559c0040c751df36b4390bd3/
- https://www.data.gouv.fr/fr/organizations/559c07ffc751df6d14390bd3/
- https://www.data.gouv.fr/fr/organizations/6511605c27356de83427f4cb/
- https://www.data.gouv.fr/fr/organizations/558bef88c751df1fd9a453b9/

Je crois que ce sont des organisations qu'on a retirées temporairement de l'univers (@streino ?). Les jeux de données sont toujours dans l'univers car on n'a pas fait de reset du topic.

A voir comment on rattrape le coup :
- reset topic
- ignorer, ça reviendra quand on les intégrera, mais en attendant les stats seront fausses, notamment le nombre de DREAL
- marquer comme deleted via #30 les organisations qui ne sont plus dans le grist (et les jeux de données en cascade) — et quand même reset Topic à un moment (idéalement régulièrement) parce qu'on sera dans un état incohérent

**Comment by streino** [comment]
https://www.data.gouv.fr/fr/organizations/6511605c27356de83427f4cb/ (DRIEAT) c'est un retrait temporaire. Par contre les autres correspondent à d'anciennes régions, je sais pas si on les ajoutera, si on consolidera sur les nouvelles régions, ou si on supprimera les données.

J'aurais tendance à préférer l'option 3 mais c'est la plus complexe à mettre en oeuvre. Sinon option 1, mais il faudra caler le timing ou trouver un moyen de reset sans (trop de downtime).

**Comment by DanFluture275** [comment]
> > Et la metrique calculée vaut 175
> 
> Celui-là c'est bon, il manque un `organization is not null` dans le Count. #34

@abulte, je comprends pas trop ton retour, la métrique `nb_organizations` est pas liée à une organisation et a une organization null.
Du coup, le is not null serait plutôt à implémenter dans la moulinette...

<img width="1097" alt="image" src="https://github.com/user-attachments/assets/c7af0e96-15ea-4e0a-974a-dc2c8d51e6e5" />

**Comment by abulte** [comment]
Avec https://github.com/opendatateam/udata/pull/3228 on pourra faire un sync/reset quotidien du topic 🤞 

Ca me parait être le mieux : moins de complexité à gérer dans la moulinette et pas de désynchro vs univers.

**Comment by abulte** [comment]
En attendant, on peut certainement supprimer "manuellement" les jeux de données concernés du Topic ?

**Comment by abulte** [comment]
```
dashboard_backend_prod=# select dataset_id from catalog where organization in ('559c0040c751df36b4390bd3', '559c07ffc751df6d14390bd3', '6511605c27356de83427f4cb', '558bef88c751df1fd9a453b9');
        dataset_id
--------------------------
 559c02e3c751df36b4390bd9
 652d04bd41b04e798e6a21e2
 559c02e488ee385c1e764f6a
 559c08adc751df6d14390bdd
 559c033388ee380e2d764f62
 559c08ac88ee385c1e764f7b
 56016347c751df255c8dabf1
 559c034088ee385c1e764f71
 559c02fbc751df484b390be2
(9 rows)
```

**Comment by abulte** [comment]
Fait en prod sur ces jeux de données ⬆️

**Comment by abulte** [comment]
Et en démo sur ⬇️ 

```
dashboard_backend=# select dataset_id from catalog where organization in ('559c0040c751df36b4390bd3', '559c07ffc751df6d14390bd3', '6511605c27356de83427f4cb', '558bef88c751df1fd9a453b9') and deleted = false;
        dataset_id
--------------------------
 559c02fbc751df484b390be2
 56016347c751df255c8dabf1
 559c034088ee385c1e764f71
 559c02e3c751df36b4390bd9
 559c08ac88ee385c1e764f7b
 559c02e488ee385c1e764f6a
 559c08adc751df6d14390bdd
 559c033388ee380e2d764f62
(8 rows)
```
